CONFIG = {
    "dataset_name": "Anthropic/hh-rlhf",
    "dataset_config": None,
    "base_model_name": "Qwen/Qwen2.5-1.5B-Instruct",
    "reward_model_name": "sunnycloudhust/Qwen2.5-3B-Instruct-Reward-Model",
    "output_dir": "outputs/reward_model_hh_rlhf",
    "reward_model_hf_repo": "sunnycloudhust/Qwen2.5-0.5B-Instruct-Reward-Model",
    "experiment_output_dir": "outputs/test_time_alignment",
    "gpu_ids": [0, 1],
    "max_length": 256,
    "epochs": 2,
    "learning_rate": 2e-5,
    "weight_decay": 0.01,
    "batch_size": 2,
    "gradient_accumulation_steps": 8,
    "eval_ratio": 0.10,
    "test_ratio": 0.10,
    "max_train_samples": 25000,
    "max_eval_samples": 1000,
    "max_test_samples": 1000,
    "num_candidates": [1, 2, 4, 8],
    "generation_max_new_tokens": 128,
    "generation_temperature": 0.8,
    "generation_top_p": 0.95,
}
